export enum WsMethod {
    PANEL_DATA = "panelData",
    BIND_PANEL = "bindPanel",
    BIND_PANEL_DISMISS = "bindPanelDismiss",
    UNBIND_PANEL = "unbindPanel",
    UNBIND_AND_CLEAR_PANEL = "unbindPanelAndClearSettings",
    CLEAR_PANEL = "clearPanelSettings",
    GET_PANEL_CHANGES = "panelChanges",
    OPEN_PANEL_SESSION = "openPanelSession",
    CLOSE_PANEL_SESSION = "closePanelSession",
    REGISTER_KEY_FOB = "registerKeyFob",

    REGISTER_ANY_PERIPHERAL = "registerAnyExtender",
    REGISTER_SENSOR = "registerSensor",
    REGISTER_KEYBOARD = "registerKeyboard",
    REGISTER_MOBILE_ID = "registerMobileID",//@deprecated
    REGISTER_STOP = "registerStop",
    UPDATE_USER = "updateUser",
    UPDATE_KEYFOB = "updateKeyFob",
    UPDATE_SENSOR = "updateSensor",
    UPDATE_REPEATER = "updateRepeater",
    UPDATE_ZONE_EXTENDER = "updateZoneExtender",
    UPDATE_KEYBOARD = "updateKeyboard",
    UPDATE_RELAY = "updateRelay",
    UPDATE_GROUP = "updateGroup",
    UPDATE_PANEL = "updatePanel",
    UPDATE_PANEL_FIRMWARE = "updatePanelFirmware",
    REMOVE_KEYBOARD = "removeKeyboard",
    REMOVE_SENSOR = "removeSensor",
    REMOVE_GROUP = "removeGroup",
    REMOVE_USER = "removeUser",
    REMOVE_REPEATER = "removeRepeater",
    REMOVE_ZONE_EXTENDER = "removeZoneExtender",
    REMOVE_RELAY = "removeRelay",
    REMOVE_KEY_FOB = "removeKeyFob",
    UPDATE_ALARM_SERVER = "updateAlarmServer",
    UPDATE_ENGINEER_CODE = "updateEngineerCode",
    HISTORY = "history",
    RESTART = 'restartPanel',

    SCAN_WIFI_AP = "scanWiFiAccessPoints"
}